name: Update PortableApps.com Launcher

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: PortableApps.com Launcher Version

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download the package
        id: download
        run: curl "https://download2.portableapps.com/portableapps/PortableApps.comLauncher/PortableApps.comLauncher_${{ github.event.inputs.version }}.paf.exe" -o PortableAppsLauncher.paf.exe

      - name: Attest the package
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: PortableAppsLauncher.paf.exe

      - name: Release the package
        id: release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          tag_name: PortableAppsLauncher/${{ github.event.inputs.version }}
          files: |
            PortableAppsLauncher.paf.exe
            ${{ steps.attest.outputs.bundle-path }}
